[env:genericSTM32F105RB]
platform            = ststm32
board               = genericSTM32F105RB
framework           = arduino
upload_protocol     = stlink
build_flags         = -DHAL_CAN_MODULE_ENABLED
lib_deps            = https://github.com/pazi88/STM32_CAN.git
